// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbaYsKTm6MoaRMUE3JiiP5TQWGOogW-h0',
    appId: '1:663215379066:web:8f8928ec97dfa90be561c3',
    messagingSenderId: '663215379066',
    projectId: 'study-app-c47f4',
    authDomain: 'study-app-c47f4.firebaseapp.com',
    storageBucket: 'study-app-c47f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSDpfJ7rqqqrsF8MUikflmeHkNFrrDlnk',
    appId: '1:663215379066:android:56be0b9edf409587e561c3',
    messagingSenderId: '663215379066',
    projectId: 'study-app-c47f4',
    storageBucket: 'study-app-c47f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWdZzkSY7jQdqRC1FfcBFLeru7_M8jIRg',
    appId: '1:663215379066:ios:4a90e53598c976aae561c3',
    messagingSenderId: '663215379066',
    projectId: 'study-app-c47f4',
    storageBucket: 'study-app-c47f4.appspot.com',
    iosClientId: '663215379066-16d81pcl911u18eub2qpu230p6g4hjfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWdZzkSY7jQdqRC1FfcBFLeru7_M8jIRg',
    appId: '1:663215379066:ios:4a90e53598c976aae561c3',
    messagingSenderId: '663215379066',
    projectId: 'study-app-c47f4',
    storageBucket: 'study-app-c47f4.appspot.com',
    iosClientId: '663215379066-16d81pcl911u18eub2qpu230p6g4hjfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterQuizApp',
  );
}
